### ISSUE TITLE
bundle.json ssffFiles

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/emuR#26]
The server also has to check the following fields in the DB config for SSFF files needed by the EMU-webApp:

- `EMUwebAppConfig -> perspectives -> twoDimCanvases -> twoDimDrawingDefinitions -> xSsffTrack & ySsffTrack `
- `levelDefinitions -> anagestConfig -> verticalPosSsffTrackName & velocitySsffTrackName`

My current workaround is to define a `garbagePerspective` that contains the needed SSFF tracks. This works but is a bit hacky and should not be necessary!

**Comment by raphywink** [comment]
@klausj this is already fixed isn't it?

**Comment by klausj** [comment]
No. The angestConfig check is still missing.
We have duplicate code here:

findAllTracksInDBconfigNeededByEMUwebApp() in serve_emuDB_files.R
and
get.ssfftrack.names.used.by.webapp.config() in database.DBconfig.EMUwebAppConfig.R

I would suggest to replace both functions by a new function 
tracks_used_by_DBconfig() in database.DBconfig.R

OK?

**Comment by raphywink** [comment]
I think the reason I called it that is because this function: https://github.com/IPS-LMU/IPS-EMUprot-nodeWSserver/blob/master/IPS-EMUprot-nodeWSserver.js#L131 of the IPS-EMUprot-nodeWSserver does exactly the same thing.

But that doesn't mean we can't get rid of the two functions and collapse them down into a function that is called `tracks_used_by_DBconfig()`.

**Comment by klausj** [comment]
I could  move the
findAllTracksInDBconfigNeededByEMUwebApp() function
to database.DBconfig.R and delete get.ssfftrack.names.used.by.webapp.config() in database.DBconfig.EMUwebAppConfig.R

**Comment by raphywink** [comment]
I'd say we get rid of both of them and create a new function called `get_ssffTracks_used_by_DBconfig()` in `database.DBconfig.R`
